# base image
FROM python:3.12.5

# setup working directory in container
 WORKDIR /app

# copy all files to app directory
 COPY . /app/

# command to run on container start
 CMD ["python", "calculator.py"]